# Generated by Django 4.2.23 on 2025-06-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('feedbacks', models.IntegerField()),
                ('basic_price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('wb_wallet_price', models.IntegerField()),
            ],
        ),
    ]
